sudo: required

language: c

services:
  - docker
  
env: SH="docker exec -t travis-test-image bash -c"

before_install:
  - docker build -t travis-test .
  - docker run -t -d --rm -v $(pwd):/opt/workspace/ -w /opt/workspace --name travis-test-image travis-test
  - docker ps -a
  
install:
  - $SH "chmod +x test.sh"
  - $SH "ls -l "

script:
  - $SH "/opt/workspace/test.sh build"
